@startuml
'https://plantuml.com/component-diagram



  [WebApp]..>  [Core.Domain]
  [DomainServices]..> [Core.Domain]
  [ApplicationServices]--() IService 
  [Infrastructure.DB]--() IRepository
  [Infrastructure.API]--() IWebRepository
  [DomainServices]--() IUserService
  
  [ApplicationServices] ..> [Core.Domain]
  [ApplicationServicesTests] ..> [Core.Domain]
  [ApplicationServicesTests] ..> [ApplicationServices]

  IService )-- [WebApp] 
  IRepository )-- [WebApp] 
  IUserService )-- [WebApp] 
  IWebRepository )-- [WebApp] 
  IRepository )-- [StamApi]
  [StamApi]..> [Core.Domain]
  
    

  
  [Infrastructure.DB] ..> [Core.Domain]
  [Infrastructure.API] ..> [Core.Domain]


@enduml