@startuml
'https://plantuml.com/component-diagram



  [AppDatabase]
  [StamDatabase]
  [IdentityDatabase]
  [Core.Domain]
  [DomainServices]
  [ApplicationServices]
  [Infrastructure.DB]
  [Infrastructure.API]
  [StamApi]
  [WebApp]





@enduml